// RootLayout.tsx
import React from "react";
import { ReactProvider } from "./ReactProvider"; // Path to your ReactProvider component
import "./globals.css";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools"; 

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ReactProvider>
      <html lang="en">
        <body>{children}</body>
      </html>
      <ReactQueryDevtools  />
    </ReactProvider>
  );
}
